Trips/Trips2/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Trips.Models
{
    public class Trip
    {
        public int Id { get; set; }

        [Display(Name = "Sihtkoht")]
        public string Destination { get; set; }

        [Display(Name = "Alguskuupäev")]
        [DataType(DataType.Date)]
        public DateTime DepartureDate { get; set; }

        [Display(Name = "Lõppkuupäev")]
        [DataType(DataType.Date)]
        public DateTime ArrivalDate { get; set; }
        //
        [Display(Name = "Majutuskulud")]
        public double HousingExpenses { get; set; }


        [Display(Name = "Transpordikulud")]
        public double TransportExpenses { get; set; }

        [Display(Name = "Muud kulud")]
        public double OtherExpenses { get; set; }

        public byte[] Picture { get; set; }

        public bool isSubmitted { get; set; }


        public int? PersonId { get; set; }

        
        //iga reisi küljes on person: vt.person.cs
        public Person Person { get; set; }












    }
}

Trips/Trips2/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Trips.Models;

namespace Trips.Controllers
{
    public class TripsController : Controller
    {
        private TripsContext db = new TripsContext();

        // GET: Trips
        public ActionResult Index()
        {

            return View(db.Trips.ToList());
            
        }


        // GET: Trips/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }



        
        // GET: Trips/Create
        public ActionResult Create(int id)
        {
            var  person = db.People.Find(id);
            
            ViewBag.PersonId = person.Id;            
            ViewBag.PersonName = person.FirstName + " " + person.LastName;
            
            return View();
        }

        // POST: Trips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Destination,DepartureDate,ArrivalDate,HousingExpenses,TransportExpenses,OtherExpenses,PersonId")] Trip trip)
        {
            
            if (ModelState.IsValid)
            {
                db.Trips.Add(trip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }           
            
            return View(trip);
        }

        // GET: Trips/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Trips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Destination,DepartureDate,ArrivalDate,HousingExpenses,TransportExpenses,OtherExpenses,PersonId")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trip);
        }

        // GET: Trips/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trip trip = db.Trips.Find(id);
            db.Trips.Remove(trip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FileUpload(HttpPostedFileBase file, int id)
        {
            Trip trip = db.Trips.Find(id);
            if (file != null)
            {
                                // save the image path path to the database or you can send image
                // directly to database
                // in-case if you want to store byte[] ie. for DB
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                    trip.Picture = array;

                    db.Entry(trip).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("index");
                }




            }
            // after successfully uploading redirect the user
            return Content("Unustasid faili valida");
            
        }

        public ActionResult Show(int id)
        {
            var trip = db.Trips.Find(id);

            if (trip.Picture == null)
            {
                return Content("Pilti pole");
            }


            return File(trip.Picture, "image/jpg");
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trips/Trips2/Views/Trips/Create.cshtml
@model Trips.Models.Trip

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sisesta uus reis</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            
            <div class="col-md-10">
                @ViewBag.PersonName
            </div>
        </div>

        @Html.Display("PersonId", (int)ViewBag.PersonId)


        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HousingExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HousingExpenses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HousingExpenses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransportExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransportExpenses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransportExpenses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherExpenses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherExpenses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <hr />
    @Html.ActionLink("Tagasi", "Index", "Trip", new { @class = "btn btn-default btn-large" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trips/Trips2/Views/Trips/Delete.cshtml
@model Trips.Models.Trip

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kustuta</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HousingExpenses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HousingExpenses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransportExpenses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransportExpenses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherExpenses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherExpenses)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <hr />
            @Html.ActionLink("Tagasi", "Index", "Trip", new { @class = "btn btn-default btn-large" })
        </div>
    }
</div>

Trips/Trips2/Views/Trips/Details.cshtml
@model Trips.Models.Trip

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detailne vaade</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.FirstName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HousingExpenses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HousingExpenses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransportExpenses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransportExpenses)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherExpenses)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherExpenses)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Muuda", "Edit", new { id = Model.Id }, new { @class = "btn btn-default btn-large" })
    <hr />
    @Html.ActionLink("Tagasi", "Index", "Trip", new { @class = "btn btn-default btn-large" })
</p>

Trips/Trips2/Views/Trips/Edit.cshtml
@model Trips.Models.Trip

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Muuda</h2>

@if (Model.Picture != null)
{
    <img src='@Url.Action("Show", "Image", new { id = Model.Id })' />
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartureDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartureDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArrivalDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HousingExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HousingExpenses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HousingExpenses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransportExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransportExpenses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransportExpenses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherExpenses, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherExpenses, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@using (Html.BeginForm("FileUpload", "Trips", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label for="file">Vali Failid:</label>
    <input type="file" name="file" id="file" style="width: 100%;" />
    @*<input type="hidden" name="tripID" id="tripID" style="width: 100%;" />*@
    @Html.HiddenFor(model => model.Id)
    <input type="submit" value="Lae üles" class="submit" />   
}
@*<div>
    @Html.CheckBox("isNewlyEnrolled", true)
</div>*@    



<div>
    <hr />
    @Html.ActionLink("Tagasi", "Index","Trip", new { @class = "btn btn-default btn-large" })
    <hr />
</div>




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trips/Trips2/Views/Trips/Index.cshtml
@model IEnumerable<Trips.Models.Trip>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reisid</h2>

<p>
    @*@Html.ActionLink("Sisesta uus reis", "Create")*@
</p>
<table class="table">
    <tr>

               
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalDate)
        </th>
        <th>
           @*@Html.DisplayNameFor(model => model.HousingExpenses)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.TransportExpenses)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.OtherExpenses)
    </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartureDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ArrivalDate)
        </td>
        <td>
           @* @Html.DisplayFor(modelItem => item.HousingExpenses)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransportExpenses)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OtherExpenses)
        </td>*@
        <td>
            @Html.ActionLink("Lisa uus","../trips/Create/", new { id = item.Id }) |
            @Html.ActionLink("Muuda", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detailne vaade", "Details", new { id=item.Id }) |
            @Html.ActionLink("Kustuta", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>